CREATE TABLE transactions_flights_items_events_v1 (
	_id bigserial PRIMARY KEY,
	airline text,
	ancillary text,
	ancillary_item_ids text,
	arrival_time_airport text,
	arrival_time_utc text,
	booking_email text,
	booking_phone text,
	booking_type text,
	cabin text,
	cancellation_airline_charge double precision,
	cancellation_charges double precision,
	cancellation_partner_airline_charge double precision,
	cancellation_paytm_charge double precision,
	cancellation_paytm_handling_fee double precision,
	cancellation_policy_charges double precision,
	cancellation_protect text,
	cancellation_protect_fee bigint,
	cancellation_protect_item_ids text,
	cancellation_protect_policy_id text,
	cancellation_provider_charge double precision,
	cancellation_reference text,
	cancellation_refund_type text,
	clc_cancellation_greater_than_2500 boolean,
	clc_cancellation_net_refund double precision,
	clc_cancellation_refund double precision,
	commissionable_value double precision,
	convenience_fee double precision,
	created_at text,
	customer_account_email text,
	customer_account_mobile text,
	customer_id bigint,
	datestr text,
	datestr_ist text,
	departure_time_airport text,
	departure_time_utc text,
	destination text,
	destination_city text,
	fare_class text,
	flight_data text,
	flight_number text,
	fuel_surcharge double precision,
	fulfillment_id bigint,
	grand_total double precision,
	is_cancellation_protect_bought boolean,
	is_cancellation_protect_eligible boolean,
	is_combination boolean,
	is_international boolean,
	is_multi_provider boolean,
	is_refundable boolean,
	is_roundtrip boolean,
	is_transaction boolean,
	is_travel_insurance_bought boolean,
	is_travel_insurance_eligible boolean,
	item_id bigint,
	journey_side text,
	merchant_id bigint,
	method text,
	mongo_id text,
	number_of_hops bigint,
	number_of_segments bigint,
	onward_airline_type text,
	onward_pnr text,
	onward_product_id bigint,
	onward_provider text,
	order_id bigint,
	origin text,
	origin_city text,
	others double precision,
	passenger_age int,
	passenger_dob text,
	passenger_firstname text,
	passenger_id text,
	passenger_lastname text,
	passenger_service_fee double precision,
	passenger_title text,
	passenger_type text,
	path text,
	paytm_cashback double precision,
	pnr text,
	price_with_convenience_fee double precision,
	price_without_convenience_fee double precision,
	product_id bigint,
	promo_code text,
	provider text,
	provider_reference text,
	raw_cancellation_policy text,
	refund_amount double precision,
	refund_mode text,
	refund_processed_date_ist text,
	refund_processing_time double precision,
	refund_reason text,
	refund_type text,
	refundable text,
	request_id text,
	return_airline_type text,
	return_pnr text,
	return_product_id bigint,
	return_provider text,
	return_requested_date_ist text,
	status int,
	tax_break_up text,
	ticket text,
	total_ancillary_price bigint,
	total_tax double precision,
	travel_date text,
	travel_insurance text,
	travel_insurance_fee bigint,
	travel_insurance_item_ids text,
	travel_insurance_policy_id text,
	trip_type text,
	updated_at text,
	user_development_fee double precision,
	vertical_id bigint,
	etl_parse_errors text,
	etl_processed_at double precision
);

// CREATE TABLE transactions_flights_items_events_v1 (_id bigserial PRIMARY KEY, airline text, ancillary text, ancillary_item_ids text, arrival_time_airport text, arrival_time_utc text, booking_email text, booking_phone text, booking_type text, cabin text, cancellation_airline_charge double precision, cancellation_charges double precision, cancellation_partner_airline_charge double precision, cancellation_paytm_charge double precision, cancellation_paytm_handling_fee double precision, cancellation_policy_charges double precision, cancellation_protect text, cancellation_protect_fee bigint, cancellation_protect_item_ids text, cancellation_protect_policy_id text, cancellation_provider_charge double precision, cancellation_reference text, cancellation_refund_type text, clc_cancellation_greater_than_2500 boolean, clc_cancellation_net_refund double precision, clc_cancellation_refund double precision, commissionable_value double precision, convenience_fee double precision, created_at text, customer_account_email text, customer_account_mobile text, customer_id bigint, datestr text, datestr_ist text, departure_time_airport text, departure_time_utc text, destination text, destination_city text, fare_class text, flight_data text, flight_number text, fuel_surcharge double precision, fulfillment_id bigint, grand_total double precision, is_cancellation_protect_bought boolean, is_cancellation_protect_eligible boolean, is_combination boolean, is_international boolean, is_multi_provider boolean, is_refundable boolean, is_roundtrip boolean, is_transaction boolean, is_travel_insurance_bought boolean, is_travel_insurance_eligible boolean, item_id bigint, journey_side text, merchant_id bigint, method text, mongo_id text, number_of_hops bigint, number_of_segments bigint, onward_airline_type text, onward_pnr text, onward_product_id bigint, onward_provider text, order_id bigint, origin text, origin_city text, others double precision, passenger_age int, passenger_dob text, passenger_firstname text, passenger_id text, passenger_lastname text, passenger_service_fee double precision, passenger_title text, passenger_type text, path text, paytm_cashback double precision, pnr text, price_with_convenience_fee double precision, price_without_convenience_fee double precision, product_id bigint, promo_code text, provider text, provider_reference text, raw_cancellation_policy text, refund_amount double precision, refund_mode text, refund_processed_date_ist text, refund_processing_time double precision, refund_reason text, refund_type text, refundable text, request_id text, return_airline_type text, return_pnr text, return_product_id bigint, return_provider text, return_requested_date_ist text, status int, tax_break_up text, ticket text, total_ancillary_price bigint, total_tax double precision, travel_date text, travel_insurance text, travel_insurance_fee bigint, travel_insurance_item_ids text, travel_insurance_policy_id text, trip_type text, updated_at text, user_development_fee double precision, vertical_id bigint, etl_parse_errors text, etl_processed_at double precision);
